services:
  portainer-agent:
    image: portainer/agent:2.21.5
    container_name: portainer-agent
    restart: unless-stopped
    environment:
      EDGE: "1"
      EDGE_ID: "{{ portainer_edge_id }}"
      EDGE_KEY: "{{ portainer_edge_key }}"
      EDGE_INSECURE_POLL: "1"
    networks:
      - colvert
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    labels:
      # Traefik configuration for the Portainer Agent
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-agent-router.rule=Host(`{{ portainer_domain }}`)"
      - "traefik.http.routers.portainer-agent-router.entrypoints=websecure"
      - "traefik.http.routers.portainer-agent-router.tls=true"
      - "traefik.http.routers.portainer-agent-router.tls.certresolver=colvertresolver"
      - "traefik.http.services.portainer-agent-service.loadbalancer.server.port=9001"
      - "traefik.docker.network=colvert"

networks:
  colvert:
    external: true

volumes:
  portainer_agent_data:
    external: true

