services:
  portainer-agent:
    image: portainer/agent:2.21.5
    container_name: portainer-agent
    restart: unless-stopped
    environment:
      EDGE: "1"
      EDGE_ID: "dd5b5e19-30d4-4233-a752-2906cdca8c22"
      EDGE_KEY: "aHR0cHM6Ly9wb3J0YWluZXIuaW5mcmEuY29sdmVydC5haXxlZGdlLmluZnJhLmNvbHZlcnQuYWk6ODAwMHwyWHJCcVFVaUhJM2FMb2svemg0Y1NsSEk5NEVMbUM5STdIUG5KenFEMlhzPXwyMQ"
      EDGE_INSECURE_POLL: "1"
    networks:
      - colvert
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    labels:
      # Traefik configuration for the Portainer Agent
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-agent-router.rule=Host(`portainer.jenkins.colvert.ai`)"
      - "traefik.http.routers.portainer-agent-router.entrypoints=websecure"
      - "traefik.http.routers.portainer-agent-router.tls=true"
      - "traefik.http.routers.portainer-agent-router.tls.certresolver=colvertresolver"
      - "traefik.http.services.portainer-agent-service.loadbalancer.server.port=9001"
      - "traefik.docker.network=colvert"

networks:
  colvert:
    external: true

volumes:
  portainer_agent_data:
    external: true

