---
- name: Check and Install Docker on Ubuntu
  hosts: servers
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: true