---
- name: Install ColvertCV App
  hosts: servers
  become: true
  tasks:
    - name: Create colvertcv directory
      file:
        path: /opt/containers/colvertcv
        state: directory
        mode: '0755'

    - name: Copy ColvertCV application files
      copy:
        src: colvertcv/
        dest: /opt/containers/colvertcv/
        mode: '0755'

    - name: Generate .env file from template
      template:
        src: colvertcv/.env.j2
        dest: /opt/containers/colvertcv/.env
        mode: '0644'
        owner: root
        group: root
        
    - name: Create compose.yml from template
      template:
        src: colvertcv/compose.yml
        dest: /opt/containers/colvertcv/compose.yml
        mode: '0644'
        owner: root
        group: root

    - name: Start ColvertCV containers
      community.docker.docker_compose_v2:
        project_src: /opt/containers/colvertcv
        state: present
        build: yes
        remove_orphans: yes