---
- name: Install ColvertCV App
  hosts: servers
  become: true
  tasks:
    - name: Create colvertcv directory
      file:
        path: /opt/containers/colvertcv
        state: directory
        mode: '0755'

    - name: Copy ColvertCV application files
      copy:
        src: colvertcv/
        dest: /opt/containers/colvertcv/
        mode: '0755'
        recursive: yes

    - name: Create .env file from template
      template:
        src: colvertcv/.env
        dest: /opt/containers/colvertcv/.env
        mode: '0644'
        owner: root
        group: root

    - name: Create docker-compose.yml from template
      template:
        src: colvertcv/docker-compose.yml
        dest: /opt/containers/colvertcv/docker-compose.yml
        mode: '0644'
        owner: root
        group: root

    - name: Start ColvertCV containers
      docker_compose:
        project_src: /opt/containers/colvertcv
        state: present
        build: yes
        remove_orphans: yes 