services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - "no-new-privileges=true" 
    command:
#      - "--pilot.dashboard=false"
#      - "--log.level=DEBUG"
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=colvert"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.colvertresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.colvertresolver.acme.email={{ traefik_email }}"
      - "--certificatesresolvers.colvertresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.forwardedHeaders.headers.customRequestHeaders.X-Forwarded-Proto=https"
      #Internal Traefik Dashboard 
      - "traefik.http.routers.dashboard.rule=Host(`{{ traefik_domain }}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.tls.certresolver=colvertresolver"
      #Middelware: Redirect to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      #Middleware: Auth Traefik Dashboard
      - "traefik.http.middlewares.auth.basicauth.users={% for user in traefik_auth_users %}{{ user.username }}:{{ user.password }}{% if not loop.last %},{% endif %}{% endfor %}"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - colvert
networks:
  colvert:
    external: true

